version: 2.1

orbs:
  aws-cli: circleci/aws-cli@0.1.13

jobs:
  deploy:
    working_directory: ~/repo

    docker:
      - image: cimg/node:14.4

    steps:
      - checkout

      - run:
          name: Installing Deployment Dependencies
          working_directory: /
          command: |
            sudo apt-get -y -qq update
            sudo apt-get install convmv
            sudo apt-get -y install python3-pip python3-dev g++ build-essential
            pip3 install --upgrade pip
            sudo apt-get remove python-pip
            pip3 install --upgrade setuptools pytz
            pip3 install awsebcli==3.10.0
            pip3 install boto3

      - aws-cli/install
      - aws-cli/configure

      - run:
          name: npm install
          command: npm install
      - run:
          name: npm run build
          command: npm run build

      - run:
          name: deploy
          command: aws s3 sync public/ s3://epi-sim/ --delete

      - run:
          name: Create Invalidation
          command: |
            aws cloudfront create-invalidation \
              --distribution-id ERS67QUBTTVQZ \
              --paths "/*"

workflows:
  version: 2
  build:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master

      - deploy:
          filters:
            branches:
              only:
                - dev
